# ?? ??
logging:
  file:
    name: /logs/file-extension-blocker.log # ??? ??? ?? ??
  level:
    jdbc:
      resultsettable: debug # SQL ?? ??? ?? ??
      sqlonly: debug # SQL ??? ??
      sqltiming: debug # SQL ?? ?? ??
    org:
      hibernate:
        orm:
          jdbc:
            bind: trace # SQL ? ??? ? ??
        sql: debug # Hibernate SQL ?? ??
      root: info # ?? ?? ??

# ?? ?? ??
server:
  port: 8080 # ?? ?? ??
  address: 0.0.0.0
  servlet:
    context-path: / # ?? url ?? ??

# ??? ??
spring:
  application:
    name: file-extension-blocker

  # DataBase ?? ??
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver # MySQL ????
    url: jdbc:mysql://127.0.0.1:3306/file_ext_blocker?serverTimezone=Asia/Seoul&characterEncoding=UTF-8 # MySQL ?????? URL
    username: root # DB ??? ID
    password: "Rlaalsgml312!" # DB ????

  devtools:
    livereload: # ?? ?? ? ???? ??????? ????? ??
      enabled: true # ?? ?? ? ?? ????

  # Spring Data JPA ??
  # JPA (Java Persistence API)
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update # DB ??? ?? ????
    show_sql: true # SQL ??? ??
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect # dialect - ?????? ? ??? SQL ??? ???? ??
        format_sql: true # SQL ?? ?? ??

  # ??????? ???? ??? ?? ? ????? ????
  # ?? ?? ???? ??? ?? ?? ? ? ???
  # ?? ???? ?? ?? ??? ??? ?? (?? ? true ??)
  thymeleaf:
    cache: false
    prefix: classpath:/templates/ # HTML ?? ?? (classpath ? resource ???? ???)
    # ?????? ??? ? ???? classpath:/templates/[???].html ?? ?? ???


  # ?? ??? ?? ??
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  # ??? ??
  jackson:
    time-zone: Asia/Seoul
    date-format: yyyy-MM-dd HH:mm:ss

  file:
    extension:
      policy:
        # ????? ???? ?? ?? ????
        # ??? ?? ?? ?? ? ??? ???? ?????? ???
        fixed-extensions:
          - bat
          - cmd
          - com
          - cpl
          - exe
          - scr
          - js
        # ??? ??? ?? ????
        max-custom-extensions: 200
        max-extension-length: 20